version: "3.8"

services:
  web:
    build:
      context: . # El punto indica que el Dockerfile está en la raíz
      dockerfile: Dockerfile
    container_name: mi_apache
    volumes:
      - ./www/isla-transfers-laravel:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    command: >
      bash -c "sed -ri -e 's!/var/www/html!/var/www/html/public!g' 
      /etc/apache2/sites-available/000-default.conf && apache2-foreground"

  db:
    image: mysql:8
    container_name: islatransfers
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: islatransfers_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3310:3306"
    # Agregamos la persistencia de datos en un volumen:
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpass
    ports:
      - "8080:80"
    depends_on:
      - db

  wordpress:
    image: wordpress:latest
    container_name: mi_wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: userpass
      WORDPRESS_DB_NAME: PHPeros_db
    ports:
      - "8081:80"

# Declaramos el volumen para almacenar los datos de la BD
volumes:
  db_data:
