version: "3.8"

services:
  web:
    build:
      context: . # El Dockerfile está en la raíz
      dockerfile: Dockerfile
    container_name: mi_apache
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      # Opcional en desarrollo (quita esto si haces entrega o build limpio)
      - ./www/isla-transfers-laravel:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf

  db:
    image: mysql:8
    container_name: islatransfers
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: islatransfers_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpass
    ports:
      - "8080:80"
    depends_on:
      - db

  wordpress:
    image: wordpress:latest
    container_name: mi_wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: userpass
      WORDPRESS_DB_NAME: islatransfers_db
    ports:
      - "8081:80"

volumes:
  db_data:
